name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  IMG: acrcanipullci.azurecr.io/canipull:latest

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - name: Build the Docker image
      run: make docker-build

    - name: Azure Container Registry Login
      if: github.event_name == 'push'
      uses: Azure/docker-login@15c4aadf093404726ab2ff205b2cdd33fa6d054c # v2
      with:
        login-server: acrcanipullci.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Push to CI ACR
      if: github.event_name == 'push'
      run: make docker-push
